-- ============================================================
-- 000_run_all_setup.sql
-- One-shot setup for Saadho Bodhashala Dashboard (001 -> 006)
--
-- How to use:
-- 1) Open Supabase SQL Editor
-- 2) Paste this entire file and run it once
-- 3) Replace v_admin_email below before running
-- ============================================================

-- ----------------------------
-- 001_dashboard_snapshots.sql
-- ----------------------------
create table if not exists public.dashboard_snapshots (
  id bigint generated by default as identity primary key,
  program_id text not null unique,
  project_name text,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_dashboard_snapshot_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dashboard_snapshots_updated_at on public.dashboard_snapshots;
create trigger trg_dashboard_snapshots_updated_at
before update on public.dashboard_snapshots
for each row
execute function public.set_dashboard_snapshot_updated_at();

alter table public.dashboard_snapshots enable row level security;

drop policy if exists "dashboard_snapshots_select_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_select_anon"
on public.dashboard_snapshots
for select
to anon
using (true);

drop policy if exists "dashboard_snapshots_insert_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_insert_anon"
on public.dashboard_snapshots
for insert
to anon
with check (true);

drop policy if exists "dashboard_snapshots_update_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_update_anon"
on public.dashboard_snapshots
for update
to anon
using (true)
with check (true);

-- -------------
-- 002_rbac.sql
-- -------------
create table if not exists public.user_roles (
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null check (role in ('admin', 'facilitator', 'sadhak', 'guest')),
  created_at timestamptz not null default now(),
  primary key (user_id)
);

alter table public.user_roles enable row level security;

drop policy if exists "user_roles_select_own" on public.user_roles;
create policy "user_roles_select_own"
  on public.user_roles
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.get_my_role()
returns text
language sql
security definer
stable
as $$
  select role from public.user_roles where user_id = auth.uid();
$$;

drop policy if exists "dashboard_snapshots_select_anon" on public.dashboard_snapshots;
drop policy if exists "dashboard_snapshots_insert_anon" on public.dashboard_snapshots;
drop policy if exists "dashboard_snapshots_update_anon" on public.dashboard_snapshots;

drop policy if exists "dashboard_snapshots_select_auth" on public.dashboard_snapshots;
create policy "dashboard_snapshots_select_auth"
  on public.dashboard_snapshots
  for select
  to authenticated
  using (public.get_my_role() in ('admin', 'facilitator'));

drop policy if exists "dashboard_snapshots_insert_admin" on public.dashboard_snapshots;
create policy "dashboard_snapshots_insert_admin"
  on public.dashboard_snapshots
  for insert
  to authenticated
  with check (public.get_my_role() = 'admin');

drop policy if exists "dashboard_snapshots_update_admin" on public.dashboard_snapshots;
create policy "dashboard_snapshots_update_admin"
  on public.dashboard_snapshots
  for update
  to authenticated
  using  (public.get_my_role() = 'admin')
  with check (public.get_my_role() = 'admin');

drop policy if exists "dashboard_snapshots_delete_admin" on public.dashboard_snapshots;
create policy "dashboard_snapshots_delete_admin"
  on public.dashboard_snapshots
  for delete
  to authenticated
  using (public.get_my_role() = 'admin');

-- ----------------------------
-- 003_program_permissions.sql
-- ----------------------------
create table if not exists public.user_program_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  program_id text not null,
  role text not null check (role in ('facilitator', 'sadhak', 'guest', 'admin')),
  created_at timestamptz not null default now(),
  primary key (user_id, program_id)
);

alter table public.user_program_roles enable row level security;

drop policy if exists "user_program_roles_select_own" on public.user_program_roles;
create policy "user_program_roles_select_own"
  on public.user_program_roles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_program_roles_insert_admin" on public.user_program_roles;
create policy "user_program_roles_insert_admin"
  on public.user_program_roles
  for insert
  to authenticated
  with check (public.get_my_role() = 'admin');

drop policy if exists "user_program_roles_update_admin" on public.user_program_roles;
create policy "user_program_roles_update_admin"
  on public.user_program_roles
  for update
  to authenticated
  using (public.get_my_role() = 'admin')
  with check (public.get_my_role() = 'admin');

drop policy if exists "user_program_roles_delete_admin" on public.user_program_roles;
create policy "user_program_roles_delete_admin"
  on public.user_program_roles
  for delete
  to authenticated
  using (public.get_my_role() = 'admin');

drop policy if exists "dashboard_snapshots_select_auth" on public.dashboard_snapshots;
drop policy if exists "dashboard_snapshots_insert_admin" on public.dashboard_snapshots;
drop policy if exists "dashboard_snapshots_update_admin" on public.dashboard_snapshots;
drop policy if exists "dashboard_snapshots_delete_admin" on public.dashboard_snapshots;

drop policy if exists "dashboard_snapshots_select_program_scoped" on public.dashboard_snapshots;
create policy "dashboard_snapshots_select_program_scoped"
  on public.dashboard_snapshots
  for select
  to authenticated
  using (
    public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_snapshots.program_id
        and upr.role in ('facilitator', 'sadhak', 'admin')
    )
  );

drop policy if exists "dashboard_snapshots_insert_program_scoped" on public.dashboard_snapshots;
create policy "dashboard_snapshots_insert_program_scoped"
  on public.dashboard_snapshots
  for insert
  to authenticated
  with check (
    public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_snapshots.program_id
        and upr.role in ('facilitator', 'admin')
    )
  );

drop policy if exists "dashboard_snapshots_update_program_scoped" on public.dashboard_snapshots;
create policy "dashboard_snapshots_update_program_scoped"
  on public.dashboard_snapshots
  for update
  to authenticated
  using (
    public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_snapshots.program_id
        and upr.role in ('facilitator', 'admin')
    )
  )
  with check (
    public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_snapshots.program_id
        and upr.role in ('facilitator', 'admin')
    )
  );

drop policy if exists "dashboard_snapshots_delete_admin_only" on public.dashboard_snapshots;
create policy "dashboard_snapshots_delete_admin_only"
  on public.dashboard_snapshots
  for delete
  to authenticated
  using (public.get_my_role() = 'admin');

-- ----------------------------
-- 004_admin_control_plane.sql
-- ----------------------------
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  city text,
  region text check (region in ('INDIA', 'NON INDIA')),
  country text,
  language text,
  group_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.user_account_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  force_password_reset boolean not null default false,
  locked_reason text,
  deactivated_reason text,
  last_password_reset_at timestamptz,
  temp_password_issued_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.user_admin_scopes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope_type text not null check (scope_type in ('global', 'program')),
  program_id text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint user_admin_scopes_shape_chk check (
    (scope_type = 'global' and program_id is null)
    or (scope_type = 'program' and program_id is not null)
  )
);

create unique index if not exists user_admin_scopes_global_uniq
  on public.user_admin_scopes (user_id, scope_type)
  where scope_type = 'global';

create unique index if not exists user_admin_scopes_program_uniq
  on public.user_admin_scopes (user_id, program_id)
  where scope_type = 'program';

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  action text not null,
  program_id text,
  reason text,
  old_value jsonb not null default '{}'::jsonb,
  new_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_target_user_id_idx on public.audit_log (target_user_id, created_at desc);
create index if not exists audit_log_actor_user_id_idx on public.audit_log (actor_user_id, created_at desc);
create index if not exists audit_log_program_id_idx on public.audit_log (program_id, created_at desc);

create table if not exists public.user_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  login_result text not null check (login_result in ('success', 'blocked_locked', 'blocked_deactivated', 'invalid_credentials', 'session_restored')),
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_login_events_created_at_idx on public.user_login_events (created_at desc);
create index if not exists user_login_events_user_id_idx on public.user_login_events (user_id, created_at desc);

create or replace function public.set_generic_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_generic_updated_at();

drop trigger if exists trg_user_account_status_updated_at on public.user_account_status;
create trigger trg_user_account_status_updated_at
before update on public.user_account_status
for each row execute function public.set_generic_updated_at();

alter table public.user_profiles enable row level security;
alter table public.user_account_status enable row level security;
alter table public.user_admin_scopes enable row level security;
alter table public.audit_log enable row level security;
alter table public.user_login_events enable row level security;

drop policy if exists "user_profiles_select_own" on public.user_profiles;
create policy "user_profiles_select_own"
  on public.user_profiles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_account_status_select_own" on public.user_account_status;
create policy "user_account_status_select_own"
  on public.user_account_status
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_admin_scopes_select_own" on public.user_admin_scopes;
create policy "user_admin_scopes_select_own"
  on public.user_admin_scopes
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "audit_log_select_admin_only" on public.audit_log;
create policy "audit_log_select_admin_only"
  on public.audit_log
  for select
  to authenticated
  using (public.get_my_role() = 'admin');

drop policy if exists "user_login_events_select_admin_only" on public.user_login_events;
create policy "user_login_events_select_admin_only"
  on public.user_login_events
  for select
  to authenticated
  using (public.get_my_role() = 'admin');

insert into public.user_account_status (user_id)
select u.id
from auth.users u
where not exists (
  select 1 from public.user_account_status s where s.user_id = u.id
);

-- ------------------------------
-- 005_seed_initial_admin.sql
-- ------------------------------
do $$
declare
  v_admin_email text := 'sanam.vishwakamal@gmail.com';
  v_user_id uuid;
begin
  select id
  into v_user_id
  from auth.users
  where lower(email) = lower(v_admin_email)
  limit 1;

  if v_user_id is null then
    raise exception 'User not found in auth.users for email: %', v_admin_email;
  end if;

  insert into public.user_roles (user_id, role)
  values (v_user_id, 'admin')
  on conflict (user_id) do update set role = excluded.role;

  insert into public.user_account_status (user_id)
  values (v_user_id)
  on conflict (user_id) do nothing;

  delete from public.user_admin_scopes
  where user_id = v_user_id;

  insert into public.user_admin_scopes (user_id, scope_type)
  values (v_user_id, 'global')
  on conflict do nothing;
end $$;

-- ----------------------------
-- 006_program_category.sql
-- ----------------------------
alter table public.dashboard_snapshots
  add column if not exists category text not null default 'General';

-- ----------------------------
-- Final verification
-- ----------------------------
select u.email, r.role, s.is_active, s.is_locked, a.scope_type, a.program_id
from auth.users u
left join public.user_roles r on r.user_id = u.id
left join public.user_account_status s on s.user_id = u.id
left join public.user_admin_scopes a on a.user_id = u.id
where lower(u.email) = lower('sanam.vishwakamal@gmail.com');
