create table if not exists public.dashboard_snapshots (
  id bigint generated by default as identity primary key,
  program_id text not null unique,
  project_name text,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_dashboard_snapshot_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dashboard_snapshots_updated_at on public.dashboard_snapshots;
create trigger trg_dashboard_snapshots_updated_at
before update on public.dashboard_snapshots
for each row
execute function public.set_dashboard_snapshot_updated_at();

alter table public.dashboard_snapshots enable row level security;

-- Basic open policies for anon key usage from dashboard clients.
-- Tighten these policies later if you add authentication.
drop policy if exists "dashboard_snapshots_select_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_select_anon"
on public.dashboard_snapshots
for select
to anon
using (true);

drop policy if exists "dashboard_snapshots_insert_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_insert_anon"
on public.dashboard_snapshots
for insert
to anon
with check (true);

drop policy if exists "dashboard_snapshots_update_anon" on public.dashboard_snapshots;
create policy "dashboard_snapshots_update_anon"
on public.dashboard_snapshots
for update
to anon
using (true)
with check (true);
