-- ============================================================
-- 004_admin_control_plane.sql  — GUI Admin Control Plane
-- Run this AFTER 003_program_permissions.sql
-- ============================================================

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  city text,
  region text check (region in ('INDIA', 'NON INDIA')),
  country text,
  language text,
  group_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.user_account_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  force_password_reset boolean not null default false,
  locked_reason text,
  deactivated_reason text,
  last_password_reset_at timestamptz,
  temp_password_issued_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.user_admin_scopes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope_type text not null check (scope_type in ('global', 'program')),
  program_id text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint user_admin_scopes_shape_chk check (
    (scope_type = 'global' and program_id is null)
    or (scope_type = 'program' and program_id is not null)
  )
);

create unique index if not exists user_admin_scopes_global_uniq
  on public.user_admin_scopes (user_id, scope_type)
  where scope_type = 'global';

create unique index if not exists user_admin_scopes_program_uniq
  on public.user_admin_scopes (user_id, program_id)
  where scope_type = 'program';

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  action text not null,
  program_id text,
  reason text,
  old_value jsonb not null default '{}'::jsonb,
  new_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_target_user_id_idx on public.audit_log (target_user_id, created_at desc);
create index if not exists audit_log_actor_user_id_idx on public.audit_log (actor_user_id, created_at desc);
create index if not exists audit_log_program_id_idx on public.audit_log (program_id, created_at desc);

create table if not exists public.user_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  login_result text not null check (login_result in ('success', 'blocked_locked', 'blocked_deactivated', 'invalid_credentials', 'session_restored')),
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_login_events_created_at_idx on public.user_login_events (created_at desc);
create index if not exists user_login_events_user_id_idx on public.user_login_events (user_id, created_at desc);

create or replace function public.set_generic_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_generic_updated_at();

drop trigger if exists trg_user_account_status_updated_at on public.user_account_status;
create trigger trg_user_account_status_updated_at
before update on public.user_account_status
for each row execute function public.set_generic_updated_at();

alter table public.user_profiles enable row level security;
alter table public.user_account_status enable row level security;
alter table public.user_admin_scopes enable row level security;
alter table public.audit_log enable row level security;
alter table public.user_login_events enable row level security;

drop policy if exists "user_profiles_select_own" on public.user_profiles;
create policy "user_profiles_select_own"
  on public.user_profiles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_account_status_select_own" on public.user_account_status;
create policy "user_account_status_select_own"
  on public.user_account_status
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_admin_scopes_select_own" on public.user_admin_scopes;
create policy "user_admin_scopes_select_own"
  on public.user_admin_scopes
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "audit_log_select_admin_only" on public.audit_log;
create policy "audit_log_select_admin_only"
  on public.audit_log
  for select
  to authenticated
  using (public.get_my_role() = 'admin');

drop policy if exists "user_login_events_select_admin_only" on public.user_login_events;
create policy "user_login_events_select_admin_only"
  on public.user_login_events
  for select
  to authenticated
  using (public.get_my_role() = 'admin');

insert into public.user_account_status (user_id)
select u.id
from auth.users u
where not exists (
  select 1 from public.user_account_status s where s.user_id = u.id
);

-- Optional manual seeds:
-- insert into public.user_admin_scopes (user_id, scope_type)
-- values ('<admin-user-uuid>', 'global')
-- on conflict do nothing;