-- 007_realtime_state_store.sql
-- Direct DB-backed key/value persistence for dashboard state.

create table if not exists public.dashboard_state_entries (
  id bigint generated by default as identity primary key,
  program_id text not null,
  state_key text not null,
  state_value jsonb not null default 'null'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dashboard_state_entries_key_uniq unique (program_id, state_key)
);

create index if not exists dashboard_state_entries_program_idx on public.dashboard_state_entries (program_id, updated_at desc);
create index if not exists dashboard_state_entries_key_idx on public.dashboard_state_entries (state_key, updated_at desc);

create or replace function public.set_dashboard_state_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.updated_by is null then
    begin
      new.updated_by = auth.uid();
    exception when others then
      new.updated_by = null;
    end;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_dashboard_state_entries_updated_at on public.dashboard_state_entries;
create trigger trg_dashboard_state_entries_updated_at
before update on public.dashboard_state_entries
for each row
execute function public.set_dashboard_state_updated_at();

alter table public.dashboard_state_entries enable row level security;

drop policy if exists "dashboard_state_entries_select_program_scoped" on public.dashboard_state_entries;
create policy "dashboard_state_entries_select_program_scoped"
  on public.dashboard_state_entries
  for select
  to authenticated
  using (
    (program_id = '__global__' and public.get_my_role() = 'admin')
    or public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_state_entries.program_id
        and upr.role in ('facilitator', 'sadhak', 'admin')
    )
  );

drop policy if exists "dashboard_state_entries_insert_program_scoped" on public.dashboard_state_entries;
create policy "dashboard_state_entries_insert_program_scoped"
  on public.dashboard_state_entries
  for insert
  to authenticated
  with check (
    (program_id = '__global__' and public.get_my_role() = 'admin')
    or public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_state_entries.program_id
        and upr.role in ('facilitator', 'admin')
    )
  );

drop policy if exists "dashboard_state_entries_update_program_scoped" on public.dashboard_state_entries;
create policy "dashboard_state_entries_update_program_scoped"
  on public.dashboard_state_entries
  for update
  to authenticated
  using (
    (program_id = '__global__' and public.get_my_role() = 'admin')
    or public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_state_entries.program_id
        and upr.role in ('facilitator', 'admin')
    )
  )
  with check (
    (program_id = '__global__' and public.get_my_role() = 'admin')
    or public.get_my_role() = 'admin'
    or exists (
      select 1
      from public.user_program_roles upr
      where upr.user_id = auth.uid()
        and upr.program_id = dashboard_state_entries.program_id
        and upr.role in ('facilitator', 'admin')
    )
  );

drop policy if exists "dashboard_state_entries_delete_admin_only" on public.dashboard_state_entries;
create policy "dashboard_state_entries_delete_admin_only"
  on public.dashboard_state_entries
  for delete
  to authenticated
  using (public.get_my_role() = 'admin');
